name: Python package

# Trigger workflow on push or pull_request
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        poetry shell
        flake8 --version
        flake8 -v .
        # poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # # Error on warnings because I'm strict
        # poetry run flake8 . --count --statistics
    - name: Check black formatting
      run: |
        poetry run black --check .
    - name: Test with pytest
      run: |
        poetry run pytest
