name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        name: Upload Release
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-python@v2

            - name: Install Poetry
              run: pip install poetry

            - name: Publish to PyPI
              env:
                  POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
              run: poetry publish --build
